### PR TITLE
Add `onTargetClick` prop

### PR DESCRIPTION
**Pull request by IanVS**
## Description

The main goal here is to add an `onTargetClick` prop, which will accept a function.  If provided, the function will be called when the user clicks on the tooltip's target element.  The function will be provided a reference to the target element, as well as a callback which the function will need to call when it is finished.  When the callback is executed, the target will receive a click as usual so that the default action of the target happens.

This also allows `onTargetClick` to be specified on a particular step instead of as a prop to the whole `<Joyride />`.

### Other incidental changes

- Fixes a bug where we were trying to start the joyride before the DOM was rendered.
- Updates the test demo

## Testing

To check these changes, you can start up the test demo:

```
yarn gulp localserver
```

Then open http://localhost:8888/, open the console, start the joyride, click the button when prompted, and notice that the step advances and a message is logged in the console.

### CODE REVIEW

**Review by chriscain — APPROVED** [review]
Honestly, code looks great. Demo worked as expected as well, nice job.

Definitely not a blocker, but from a demo perspective, it might make more sense to have something visually different when utilizing the callback feature. I only knew to have my console open because I was reading over the source code. Either way, I think this is exactly what we want for target-to-page-transition interactions.

**Comment by IanVS** [comment]
Yeah, GP, the reason I didn't want to actually change anything in the DOM was because then I would have to tweak the tests, and they are very fragile, unfortunately.  The demo isn't really "public", it's just used for tests, and is helpful for developers reading through the source to figure out how it works.

**Comment by IanVS** [comment]
Don't merge just yet.  Might have found a problem.

**Comment by IanVS** [comment]
OK, fixed it.  I had forgotten to check for `onTargetClick` on the step in the `start` method.

**Pull request merged**
